apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-backend
  namespace: dwp-prod
  labels:
    app: blog-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-backend
  template:
    metadata:
      labels:
        app: blog-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: blog-backend
          image: 850756192530.dkr.ecr.us-east-1.amazonaws.com/dwp/blog:v1.4.0
          ports:
           - containerPort: 8080
          env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://dwp-platform-nonprod.ch8cowcymvme.eu-west-1.rds.amazonaws.com:5432/prodblogdb?serverTimezone=UTC
          - name: SPRING_DATASOURCE_USERNAME
            value: produser
          - name: SPRING_DATASOURCE_PASSWORD
            value: produser
          - name: SERVER_PORT
            value: "8080"



            