apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ui-to-backend-network.yaml
  - pg-pvc.yaml
  - pg-secret.yaml
  - pg-deployment.yaml
  - pg-service.yaml
  - blog-deployment.yaml
  - blog-service.yaml
  - blog-ui-deployment.yaml
  - blog-ui-service.yaml
