# authpg-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authpg-pvc
  namespace: dwp-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
