# authpg-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: authpg-secret
  namespace: dwp-dev
type: Opaque
stringData:
  POSTGRES_DB: authdb
  POSTGRES_USER: authuser
  POSTGRES_PASSWORD: authuser
