apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ui-to-backend-network-rule.yaml
  - blogpg-pvc.yaml
  - blogpg-secret.yaml
  - blogpg-deployment.yaml
  - blogpg-service.yaml
  - authpg-pvc.yaml
  - authpg-secret.yaml
  - authpg-deployment.yaml
  - authpg-service.yaml
  - blog-deployment.yaml
  - blog-service.yaml
  - auth-deployment.yaml
  - auth-service.yaml
  - dwp-ui-deployment.yaml
  - dwp-ui-service.yaml
