apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ui-to-backend-network-rule.yaml
  - auth-deployment.yaml
  - auth-service.yaml
  - blog-deployment.yaml
  - blog-service.yaml
  - dwp-ui-deployment.yaml
  - dwp-ui-service.yaml