apiVersion: v1
kind: Service
metadata:
  name: blog-frontend
  namespace: dwp-dev
  labels:
    app: blog-frontend
spec:
  selector:
    app: blog-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: LoadBalancer