apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: dwp-dev
  labels:
    app: blog-backend
spec:
  selector:
    app: blog-backend
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: http
  type: ClusterIP